sudo: required
language: ruby
services:
  - docker
before_install:
  - docker build -t 'boyddames-api' ./.
  - docker run --name psql-db -d postgres:9.4
  - docker run --rm --link psql-db:db boyddames-api rake db:create
  - docker run --rm --link psql-db:db boyddames-api rake db:migrate
script:
  - docker run --rm --link psql-db:db boyddames-api rake
